package gr.aueb.android.barista.core.utilities;

import android.os.Environment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Field;

import androidx.test.InstrumentationRegistry;
import timber.log.Timber;

/**
 * DefaultBaristaConfigurationReader is responsible for fetching configuration option provided by the Barista Plugin
 *
 */
public class BaristaConfiguration {

    private static final int DEFAULT_PORT = 8040;
    private static final String DEFAULT_HOST = "UNCONFIGURED_HOST";

    public static final String BARISTA_PORT = "BARISTA_PORT";
    public static final String BARISTA_HOST = "BARISTA_HOST";

    private String sessionToken = null;
    private String host = DEFAULT_HOST;
    private int port = DEFAULT_PORT;
    private static BaristaConfiguration theInstance = null;

    private BaristaConfiguration(){

    }

    public static BaristaConfiguration getInstance() {

        if (theInstance == null){
            theInstance = new BaristaConfiguration();
            theInstance.loadBuildConfigProperties();
        }
        return theInstance;

    }


    /**
     * Method that searches and returns the value for the BARISTA_PORT field in the BuildConfig file of the instrumented app.
     * IMPORTANT: This method must be called after the Instrumentation Registry has been initialized or else it will fail.
     *
     * @return The integer value of the port. If none provided default port 8040 will be used
     */
    private void loadBuildConfigProperties() {

        String packageName = InstrumentationRegistry.getTargetContext().getPackageName();

        String buildConfigClass = packageName + ".BuildConfig";

        try {
            Class clazz = Class.forName(buildConfigClass);
            Field portField = clazz.getField(BARISTA_PORT);
            Field hostField = clazz.getField(BARISTA_HOST);

            if (portField != null) {
                portField.setAccessible(true);
                port = (Integer) portField.get(clazz);
            }
            if (hostField != null) {
                hostField.setAccessible(true);
                host = (String) hostField.get(clazz);
            }
            Timber.d("Barista library configured for server accessible at: %s:%s", host, port);

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }

    /**
     * Reads the barista-token.txt file created by the barista plugin and returns the sessionToken provided.
     * IMPORTANT: The barista library must have the READ_EXTRERNAL_STORAGE permission granted
     * @return The sessionToken generated by the server
     */
    public String retrieveEmulatorSessionToken() {
        if(sessionToken == null) {
            File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "barista-token.txt");
            Timber.d("Searching for token at: " + file.getAbsolutePath());
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    sessionToken = line;
                }

            } catch (IOException e) {
                Timber.e("Error while trying to read the sessionToken. "+e.getMessage());
                e.printStackTrace();
            }

            return sessionToken;
        }
        else{
            Timber.d("Returning cached value.");
            return sessionToken;
        }
    }

    /**
     * Reads the barista-token.txt file created by the barista plugin and returns the sessionToken provided.
     * IMPORTANT: The barista library must have the READ_EXTRERNAL_STORAGE permission granted
     * @return The sessionToken generated by the server
     */
    //todo This is ONLY FOR POC. File name must be dynamically provided by the plugin
    public static File getPathFile() {

        File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "AthensTour.kml");
        return file;

    }

    public String getHost() {
        return host;
    }

    public int getPort() {
        return port;
    }

    public String getSessionToken() {
        return sessionToken;
    }
}

